---

- hosts: all
  become: yes
  tasks:
    - include: playbooks/dev.yml
      when: ansible_distribution == 'Ubuntu'

    #- apt: name=zsh state=latest update_cache=yes
    #- user: name=$user shell=/bin/zsh

    #- shell: /.dotfiles/install.sh
